# Generated by Django 4.0.4 on 2022-04-16 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(max_length=30, verbose_name='Name of project')),
                ('persons', models.IntegerField(verbose_name='Number of persons in project.')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField(max_length=30, verbose_name='Name of task')),
                ('days', models.IntegerField(verbose_name='Quantity of days')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectp.project')),
            ],
        ),
    ]
